name: Run Firebase and Google Sheets Script

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日午前0時に実行

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 使用するPythonバージョンを指定

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install firebase-admin google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    - name: Run script
      env:
        GOOGLE_APPLICATION_CREDENTIALS: /content/service-account.json
        FIREBASE_CREDENTIALS: /content/firebase-service-account.json
      run: |
        echo "${{ secrets.GCP_API_KEY }}" > /content/service-account.json
        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > /content/firebase-service-account.json
        python Untitled1.py  # スクリプトのファイル名を指定
